Set Shell bash
Set FontSize 18
Set Width 900
Set Height 620

Hide Sleep 1s Show

Output demo.gif

Hide
Type "clear"
Enter
Show

Type "caniuse --help"
Sleep 1s
Enter
Sleep 3s

Hide
Type "clear"
Enter
Show

Type "caniuse flexbox-gap"
Sleep 1200ms
Enter
Sleep 5s

Hide
Type "clear"
Enter
Show

Type "caniuse css-grid"
Sleep 1200ms
Enter
Sleep 5s

Hide
Type "clear"
Enter
Show

Type "caniuse avif"
Sleep 1200ms
Enter
Sleep 5s
